image: golang:1.9

variables:
  REPO_NAME: gitlab.com/$CI_PROJECT_PATH

before_script:
- mkdir -p $GOPATH/src/$(dirname $REPO_NAME)
- ln -svf $CI_PROJECT_DIR $GOPATH/src/$REPO_NAME
- cd $GOPATH/src/$REPO_NAME

stages:
  - test
  - release

test-semrel:
  stage: test
  script:
  - curl https://raw.githubusercontent.com/golang/dep/master/install.sh | sh
  - dep ensure
  - go test -cover ./semrel

test-inspectgit:
  stage: test
  script:
  - curl https://raw.githubusercontent.com/golang/dep/master/install.sh | sh
  - dep ensure
  - go test -cover ./inspectgit

test-angularcommit:
  stage: test
  script:
  - curl https://raw.githubusercontent.com/golang/dep/master/install.sh | sh
  - dep ensure
  - go test -cover ./angularcommit

trigger-release:
  stage: release
  image: registry.gitlab.com/juhani/go-semrel-gitlab:v0.10.1
  script:
    - release tag
  when: manual
  except:
    - tags